### ISSUE TITLE
Example of embed implimentation

### ISSUE THREAD

**Issue by FOCI-DEV** [Mundayne/reaction-menu#2]
Hello, could you provide a broef example or explination of how to utilize embeds in example.js? having trouble figuring it out as I am still learnin... thank you for your work

**Comment by Gyzimo** [comment]
Hey foci.  if you need help on this best is to visit 
https://github.com/Mundayne/reaction-menu

I am not the creator of this module. 
This is an older version i use in all my projects
and it has been updated a lot.  The official creator of this 
module is *Mundayne*. 

I simply uploaded this as this is the version i use in 
all my projects and i every time i installed a new module 
i forget to switch the new with the old version causing my
programs to crash and be offline for quite some time. 

Happend to much so i uploaded this package and 
changed the require dependency in my programs. 

So i cant take credit nor help you on this ;)
But feel free to contact Mundayne. 
Talked to him before, great guy and he probably 
will be able to help you.

God speed my friend !

**Comment by Mundayne** [comment]
I have been summoned...

In the most up-to-date version, you should be able to just pass a `RichEmbed` object as the message for a menu, simple as that. In this old version you also need to flag that the message being passed is an embed, which was dumb hence that change.
